spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/chrms_db
    username: chrms_user
    password: chrms_pass123
  
  data:
    redis:
      host: redis
      port: 6379

logging:
  level:
    root: INFO
    com.chrms: INFO
